// LOCALHOST 

### Home
GET http://localhost:8080/

### All pirates
GET http://localhost:8080/pirates

### pirate by Id
GET http://localhost:8080/pirates/67a820f2ac70f2e176054686
### Create pirate Post
POST http://localhost:8080/pirates HTTP/1.1
content-type: application/json

{
    "fullName": "Nico Robin", "birthPlace": "West Blue", "birthday": "02/06", "status": "Alive", "fruitType": "Paramecia", "affiliations": "StrawHat Pirate", "position": "Archaeologist"
}

### Put pirate
PUT http://localhost:8080/pirates/67a820f2ac70f2e17605468a HTTP/1.1
content-type: application/json

{
    "fullName": "Red-Hair Shanks", "birthPlace": "West Blue", "birthday": "03/09", "status": "Alive", "fruitType": "N/A", "affiliations": "Red Haired Pirate", "position": "Captain"
}

### Delete pirate
DELETE http://localhost:8080/pirates/67a8227a67cd4b73113dfa11 HTTP/1.1
content-type: application/json

### Swagger
GET http://localhost:8080/api-docs/

//Lesson 06 
### PUT
PUT http://localhost:8080/pirates/67b16ac2287b967356d2044b HTTP/1.1
Content-Type: application/json

{
    "fullName": "Eustass Kid", "birthPlace": "South Blue", "birthday": "01/10", "status": "Unknown", "fruitType": "Paramecia", "affiliations": "Kid Pirate", "position": "Captain"
}
### DELETE
DELETE http://localhost:8080/pirates/67b16ae7287b967356d2044c HTTP/1.1
Content-Type: application/json

// PRODUCTION Deploy or render.com 
### The index and Name
GET https://cse341project-heyrend.onrender.com

### pirates
GET https://cse341project-heyrend.onrender.com/pirates

### Get pirate bt Id 
GET https://cse341project-heyrend.onrender.com/pirates/67a820f2ac70f2e176054685

### Create pirate Post
POST https://cse341project-heyrend.onrender.com/pirates/ HTTP/1.1
content-type: application/json

{
    "fullName": "Nico Robin", "birthPlace": "West Blue", "birthday": "02/06", "status": "Alive", "fruitType": "Paramecia", "affiliations": "StrawHat Pirate", "position": "Archaeologist"
}
### Put pirate 
PUT https://cse341project-heyrend.onrender.com/pirates/67a820f2ac70f2e17605468a HTTP/1.1
content-type: application/json

{
    "fullName": "Shanks", "birthPlace": "West Blue", "birthday": "03/09", "status": "Alive", "fruitType": "N/A", "affiliations": "Red Haired Pirate", "position": "Captain"
}
### Delete pirate
DELETE https://cse341project-heyrend.onrender.com/pirates/67a83242fb7cd1f647153e32 HTTP/1.1
content-type: application/json

### Swagger
GET https://cse341project-heyrend.onrender.com/api-docs/

//Lesson 06
// error to show 67a8227a67cd4b73113dfa11
### PUT
PUT https://cse341project-heyrend.onrender.com/pirates/67b16c8f287b967356d2044d HTTP/1.1
Content-Type: application/json

{
    "fullName": "Eustass Kid", "birthPlace": "South Blue", "birthday": "01/10", "status": "Unknown", "fruitType": "Paramecia", "affiliations": "Kid Pirate", "position": "Captain"
}
### DELETE
DELETE https://cse341project-heyrend.onrender.com/pirates/67b16c93287b967356d2044e HTTP/1.1
Content-Type: application/json
