// LOCALHOST 

### Home
GET http://localhost:8080/

### All pirates
GET http://localhost:8080/pirates

### pirate by Id
GET http://localhost:8080/pirates/67a80eecac70f2e17605467b
### Create pirate Post
POST http://localhost:8080/pirates HTTP/1.1
content-type: application/json

{
    "fullName": "Nico Robin", "orgin": "West Blue", "birthday": "02/06", "status": "Alive", "fruitType": "Paramecia", "affiliations": "StrawHat Pirate", "position": "Archaeologist"
}

### Put pirate
PUT http://localhost:8080/pirates/67a80eecac70f2e176054680 HTTP/1.1
content-type: application/json

{
    "fullName": "Shanks", "orgin": "West Blue", "birthday": "03/09", "status": "Alive", "fruitType": "N/A", "affiliations": "Red Haired Pirate", "position": "Captain"
}

### Delete pirate
DELETE http://localhost:8080/67a81ece826f2704f267c3d2 HTTP/1.1
content-type: application/json

### Swagger
GET http://localhost:8080/api-docs/

// PRODUCTION Deploy or render.com 
### The index and Name
GET https://cse341project-heyrend.onrender.com

### pirates
GET https://cse341project-heyrend.onrender.com/pirates

### Get pirate bt Id 
GET https://cse341project-heyrend.onrender.com/pirates/67a80eecac70f2e17605467b

### Create pirate Post
POST https://cse341project-heyrend.onrender.com/pirates/ HTTP/1.1
content-type: application/json

{
    "fullName": "Nico Robin", "orgin": "West Blue", "birthday": "02/06", "status": "Alive", "fruitType": "Paramecia", "affiliations": "StrawHat Pirate", "position": "Archaeologist"
}
### Put pirate 
PUT https://cse341project-heyrend.onrender.com/pirates/67a80eecac70f2e176054680 HTTP/1.1
content-type: application/json

{
    "fullName": "Shanks", "orgin": "West Blue", "birthday": "03/09", "status": "Alive", "fruitType": "N/A", "affiliations": "Red Haired Pirate", "position": "Captain"
}
### Delete pirate
DELETE https://cse341project-heyrend.onrender.com/pirates/67a81ece826f2704f267c3d2 HTTP/1.1
content-type: application/json

### Swagger
GET https://cse341project-heyrend.onrender.com/api-docs/